
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[500] =
    {   0,
        0,    0,  107,  106,  104,  105,   67,   47,    4,   85,
       80,   46,   73,   74,   91,   84,   70,   83,   79,   93,
       96,   96,   71,   68,   86,   72,   87,   81,   95,   95,
       42,   95,   95,   95,   95,   75,   76,   88,   69,   90,
       95,   95,   95,   95,   95,   95,   95,   95,   43,   95,
       95,   95,   95,   95,   95,   95,   95,   95,   77,   89,
       78,   82,    3,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,   65,    0,  102,    0,    4,   56,   57,
        0,  102,    0,   92,   53,   44,   51,   45,   52,    0,
       99,   94,   55,   99,   97,    0,    0,  101,    0,   96,
       61,   62,   66,   64,   63,   60,   95,   95,   95,    0,
        0,   95,   95,   58,   95,   16,   95,   95,   95,   95,
       95,   95,   95,   95,   95,   95,    5,   95,   26,   27,
       95,   95,   95,   30,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   59,    3,    3,    2,    1,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
      102,    0,    0,   54,   48,   99,    0,  100,   98,   50,
       49,   95,   95,    0,   95,   15,   95,   95,   95,   95,
        7,   20,   95,   95,   95,   95,   95,    6,   95,   95,

       95,   95,   95,   29,   95,   95,   95,   95,   95,   95,
       34,   95,   95,   95,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    0,    0,
        0,    0,    0,    0,   95,   13,   14,   95,   95,   95,
       95,    9,   10,   95,   40,   95,   23,   95,   95,   95,
       95,   31,   95,   95,   95,   95,   95,   95,   36,   95,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    0,    0,   12,   95,   18,    8,   95,   95,
       95,   95,   95,   41,   95,   39,   32,   38,   95,   95,
       35,   37,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,  103,  103,   17,   95,   21,   95,   24,   25,
       28,   33,   95,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,   95,   22,   95,    3,    3,    3,
       19,   95,    3,    3,   95,    3,   11,    3,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    1,   28,   29,   29,   29,   29,   30,   31,
       32,   32,   32,   33,   32,   34,   32,   35,   32,   32,
       32,   36,   32,   37,   38,   32,   32,   39,   32,   32,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   32,   62,   63,   64,   65,   32,   66,   67,
       68,   32,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1,    1,    6,    1,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[513] =
    {   0,
        0,   72,  879,  880,  880,  880,  852,  138,    0,  851,
      850,  135,  880,  880,  133,  134,  880,  131,  132,  132,
      144,  151,  880,  880,  160,  849,  129,  880,    0,  828,
        0,  813,  156,  810,  171,  880,  880,  845,    0,  880,
      129,  808,  133,  819,  113,  135,  811,  145,  821,  806,
      803,  129,  191,  814,  801,  203,  159,  808,  880,  835,
      880,  880,    0,  213,  880,    0,  214,  834,  211,    0,
      833,  832,  213,    0,    0,  209,  206,    0,  208,  208,
      142,  225,  239,    0,    0,  223,  831,  236,    0,  294,
      810,    0,  795,  220,  792,  231,    0,    0,  827,    0,

        0,  177,  790,  196,  801,  209,  217,  793,  223,  803,
      788,  785,  222,  360,  796,  783,  361,  237,  790,    0,
      817,    0,    0,  880,  237,  835,  830,    0,  880,  880,
      358,  829,  832,  812,  880,  880,  880,  880,  880,  819,
      353,  880,  880,  357,  371,  395,  412,  880,    0,  418,
      810,  880,  880,  880,  880,  809,    0,  777,  774,  825,
      359,  766,  369,  880,  781,  766,  778,  781,  767,  331,
      234,  235,  766,  762,  763,  762,    0,  760,    0,    0,
      770,  761,  754,    0,  754,  762,  146,  751,  750,  745,
      758,  747,  760,  880,    0,  382,  880,  880,  391,    0,

      411,  802,    0,    0,    0,    0,  413,  797,    0,  781,
        0,    0,    0,    0,    0,  788,  436,    0,    0,  442,
      460,  478,  492,    0,  514,  499,  779,    0,    0,    0,
        0,  778,    0,  746,  743,  794,  424,  735,  391,    0,
      750,  735,  747,  750,  736,  354,  383,  393,  735,  731,
      732,  731,    0,  729,    0,    0,  739,  730,  723,    0,
      723,  731,  355,  720,  719,  714,  727,  716,  729,    0,
      880,  412,  419,  880,  880,  517,  463,  520,    0,  880,
      880,  715,  727,  769,  725,    0,  724,  727,  709,  707,
        0,    0,  719,  719,  718,  719,  720,    0,  707,  717,

      703,  704,  714,    0,  697,  700,  695,  705,  691,  706,
        0,  697,  700,  695,    0,  464,  484,    0,    0,  536,
      481,  556,  592,    0,    0,  688,  700,  742,  698,    0,
      697,  700,  682,  680,    0,    0,  692,  692,  691,  692,
      693,    0,  680,  690,  676,  677,  687,    0,  670,  673,
      668,  678,  664,  679,    0,  670,  673,  668,  435,  448,
      721,  433,  436,  720,  672,    0,    0,  659,  664,  656,
      664,    0,    0,  656,    0,  659,    0,  669,  652,  650,
      663,    0,  619,  627,  621,  603,  608,  607,    0,  602,
      552,  567,  644,  568,  577,  642,  587,    0,    0,  574,

      579,  571,  579,    0,    0,  571,    0,  574,    0,  583,
      566,  564,  577,    0,  560,  567,  566,  553,  560,  557,
        0,  557,  463,  438,    0,  541,    0,    0,  545,  539,
      545,  544,  536,    0,  553,    0,    0,    0,  539,  546,
        0,    0,  578,  579,    0,  530,    0,    0,  525,  519,
      516,  511,  488,    0,  505,    0,    0,    0,  489,  495,
        0,    0,  481,  483,    0,  466,    0,  462,    0,    0,
        0,    0,  481,  589,  584,    0,  461,    0,  455,    0,
        0,    0,    0,  472,  466,    0,  441,  411,    0,  394,
        0,  338,    0,  324,  209,  206,    0,    0,  880,  643,

      649,  655,  657,  663,  669,  675,  681,  246,  687,  693,
      699,  705
    } ;

static const flex_int16_t yy_def[513] =
    {   0,
      499,  499,  499,  499,  499,  499,  499,  500,  501,  499,
      499,  502,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  503,  503,
      503,  503,  503,  503,  503,  499,  499,  499,  503,  499,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  499,  499,
      499,  499,  504,  504,  499,  504,  504,  504,  505,  506,
      504,  504,  507,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  499,
       90,   90,   90,   90,   90,   90,  504,  504,  504,   90,

      504,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,  504,
      504,  504,  504,  499,  500,  499,  500,  501,  499,  499,
      502,  499,  502,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  508,  499,
      499,  499,  499,  499,  499,  499,  503,  503,  503,  499,
      502,  503,  503,  499,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  499,  504,  504,  499,  499,  504,  504,

      505,  504,  505,  506,  504,  504,  507,  504,  507,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,   90,   90,   90,  504,  507,   90,   90,  504,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,  504,
      499,  509,  510,  499,  499,  499,  499,  499,  508,  499,
      499,  503,  503,  499,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,

      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  504,  511,  512,  504,  504,  504,
      504,  504,  504,  504,  504,   90,   90,  504,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,  509,  509,
      509,  510,  510,  510,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      511,  511,  511,  512,  512,  512,   90,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,  509,  510,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  503,  503,  503,  503,  503,  503,
      503,  503,  511,  512,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,  509,  510,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  511,  512,   90,   90,   90,   90,   90,
       90,   90,   90,   90,  503,  503,  503,   90,   90,   90,
      503,  503,   90,   90,  503,   90,  503,   90,    0,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499
    } ;

static const flex_int16_t yy_nxt[953] =
    {   0,
        4,    4,    5,    6,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   23,   24,   25,   26,   27,   28,   29,   29,
       30,   29,   29,   31,   32,   33,   34,   35,   29,   36,
        4,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   29,   48,   29,   29,   49,   29,   50,   51,
       52,   53,   54,   55,   56,   57,   29,   58,   59,   60,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   83,   83,   84,   85,   86,   87,   88,   89,

       90,   90,   91,   90,   90,   92,   93,   94,   95,   96,
       90,   97,   63,   98,   99,  100,  101,  102,  103,  104,
      105,  106,  107,  108,   90,  109,   90,   90,  110,   90,
      111,  112,  113,  114,  115,  116,  117,  118,   90,  119,
      120,  121,  122,  123,  126,  132,  134,  138,  136,  140,
      142,  141,  141,  141,  155,  156,  139,  143,  135,  137,
      218,  144,  160,  145,  145,  146,  161,  219,  144,  171,
      150,  150,  150,  147,  185,  133,  148,  160,  127,  172,
      147,  161,  149,  148,  151,  152,  153,  165,  173,  168,
      186,  166,  169,  147,  174,  177,  175,  160,  148,  307,

      147,  161,  178,  179,  308,  148,  163,  180,  181,  160,
      149,  191,  192,  161,  196,  197,  198,  202,  199,  195,
      212,  195,  210,  208,  214,  216,  236,  217,  217,  217,
      237,  213,  163,  215,  211,  241,  187,  236,  163,  242,
      188,  237,  220,  271,  221,  221,  222,  227,  228,  229,
      279,  203,  244,  209,  223,  245,  220,  224,  226,  226,
      226,  231,  232,  225,  163,  247,  239,  261,  223,  498,
      249,  224,  497,  253,  223,  248,  250,  127,  251,  224,
      254,  255,  295,  262,  296,  256,  257,  293,  223,  267,
      268,  225,  239,  224,  195,  195,  294,  195,  195,  195,

      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  233,  233,  233,  195,  195,  195,  195,
      195,  195,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  195,  195,  195,  195,  233,  195,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  195,  195,  195,  195,  236,  236,  271,  132,
      237,  237,  141,  141,  141,  160,  276,  276,  276,  161,
      496,  291,  147,  196,  197,  148,  147,  292,  144,  148,
      145,  145,  146,  198,  495,  199,  239,  236,  133,  133,

      147,  237,  147,  148,  335,  263,  147,  148,  351,  264,
      336,  148,  144,  352,  146,  146,  146,  315,  360,  195,
      147,  195,  239,  315,  147,  148,  277,  148,  277,  363,
      195,  278,  278,  278,  208,  144,  337,  150,  150,  150,
      339,  360,  340,  363,  147,  338,  424,  147,  464,  148,
      148,  203,  361,  209,  423,  217,  217,  217,  494,  364,
      493,  320,  320,  320,  209,  223,  359,  147,  224,  463,
      392,  223,  148,  364,  224,  361,  364,  220,  364,  221,
      221,  222,  278,  278,  278,  223,  362,  463,  361,  223,
      224,  223,  224,  464,  395,  220,  224,  222,  222,  222,

      322,  322,  322,  361,  393,  492,  321,  223,  321,  223,
      224,  322,  322,  322,  224,  491,  220,  490,  226,  226,
      226,  361,  489,  364,  396,  488,  487,  223,  223,  486,
      485,  224,  224,  323,  323,  323,  276,  276,  276,  278,
      278,  278,  323,  323,  323,  484,  147,  483,  223,  148,
      482,  481,  148,  224,  359,  320,  320,  320,  392,  323,
      323,  323,  323,  323,  323,  223,  147,  480,  224,  359,
      362,  148,  479,  443,  148,  322,  322,  322,  395,  362,
      359,  362,  478,  477,  474,  223,  362,  444,  224,  475,
      224,  359,  393,  476,  475,  474,  473,  472,  471,  470,

      469,  468,  467,  466,  465,  462,  461,  393,  396,  460,
      224,  323,  323,  323,  459,  458,  457,  396,  393,  396,
      323,  323,  323,  456,  396,  455,  454,  453,  452,  393,
      451,  450,  449,  448,  447,  446,  445,  323,  323,  323,
      323,  323,  323,  125,  499,  125,  499,  125,  125,  128,
      442,  128,  128,  128,  128,  131,  441,  440,  131,  131,
      131,  157,  157,  195,  439,  195,  195,  195,  195,  201,
      438,  201,  201,  201,  201,  204,  437,  204,  204,  204,
      204,  207,  436,  207,  207,  207,  207,  359,  359,  359,
      359,  359,  359,  362,  362,  362,  362,  362,  362,  391,

      391,  391,  391,  391,  391,  394,  394,  394,  394,  394,
      394,  435,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  499,  499,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  403,  402,  401,  400,  399,  316,  398,
      397,  390,  389,  388,  387,  386,  385,  384,  383,  382,
      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  367,  272,  366,  365,  358,  357,
      356,  355,  354,  353,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  334,  333,  332,  331,  330,  329,

      328,  327,  326,  325,  324,  319,  318,  317,  316,  314,
      313,  312,  311,  310,  309,  306,  305,  304,  303,  302,
      301,  300,  299,  298,  297,  290,  289,  288,  287,  286,
      285,  284,  283,  282,  281,  280,  275,  274,  131,  273,
      125,  272,  270,  269,  266,  265,  260,  259,  258,  252,
      246,  243,  240,  238,  235,  234,  230,  206,  205,  200,
      194,  193,  190,  189,  184,  183,  182,  176,  170,  167,
      164,  162,  159,  158,  154,  130,  129,  124,  499,    3,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499
    } ;

static const flex_int16_t yy_chk[953] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    8,   12,   15,   18,   16,   19,
       20,   19,   19,   19,   27,   27,   18,   20,   15,   16,
       81,   21,   33,   21,   21,   21,   33,   81,   22,   45,
       22,   22,   22,   21,   52,   12,   21,   35,    8,   45,
       22,   35,   21,   22,   25,   25,   25,   41,   46,   43,
       52,   41,   43,   21,   46,   48,   46,   53,   21,  187,

       22,   53,   48,   48,  187,   22,   35,   48,   48,   56,
       21,   57,   57,   56,   64,   64,   67,   69,   67,   73,
       77,   69,   76,   73,   79,   80,   94,   80,   80,   80,
       94,   77,   35,   79,   76,  102,   53,   96,   56,  102,
       53,   96,   82,  125,   82,   82,   82,   86,   86,   86,
      508,   69,  104,   73,   82,  104,   83,   82,   83,   83,
       83,   88,   88,   82,   56,  106,   96,  113,   83,  496,
      107,   83,  495,  109,   82,  106,  107,  125,  107,   82,
      109,  109,  172,  113,  172,  109,  109,  171,   83,  118,
      118,   82,   96,   83,   90,   90,  171,   90,   90,   90,

       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,  114,  117,  131,  161,
      114,  117,  141,  141,  141,  163,  144,  144,  144,  163,
      494,  170,  141,  196,  196,  141,  144,  170,  145,  144,
      145,  145,  145,  199,  492,  199,  117,  239,  131,  161,

      145,  239,  141,  145,  246,  114,  144,  141,  263,  114,
      246,  144,  146,  263,  146,  146,  146,  201,  272,  207,
      145,  201,  117,  207,  146,  145,  147,  146,  147,  273,
      237,  147,  147,  147,  237,  150,  247,  150,  150,  150,
      248,  359,  248,  362,  146,  247,  363,  150,  424,  146,
      150,  201,  272,  207,  360,  217,  217,  217,  490,  273,
      488,  220,  220,  220,  237,  217,  316,  150,  217,  423,
      316,  220,  150,  362,  220,  359,  363,  221,  424,  221,
      221,  221,  277,  277,  277,  217,  317,  463,  360,  221,
      217,  220,  221,  464,  317,  222,  220,  222,  222,  222,

      321,  321,  321,  423,  316,  487,  223,  222,  223,  221,
      222,  223,  223,  223,  221,  485,  226,  484,  226,  226,
      226,  463,  479,  464,  317,  477,  473,  222,  226,  468,
      466,  226,  222,  225,  225,  225,  276,  276,  276,  278,
      278,  278,  225,  225,  225,  460,  276,  459,  226,  276,
      455,  453,  278,  226,  391,  320,  320,  320,  391,  225,
      225,  225,  225,  225,  225,  320,  276,  452,  320,  392,
      394,  276,  451,  392,  278,  322,  322,  322,  394,  395,
      443,  444,  450,  449,  443,  320,  475,  395,  322,  444,
      320,  474,  391,  446,  475,  474,  440,  439,  435,  433,

      432,  431,  430,  429,  426,  422,  420,  392,  394,  419,
      322,  323,  323,  323,  418,  417,  416,  395,  443,  444,
      323,  323,  323,  415,  475,  413,  412,  411,  410,  474,
      408,  406,  403,  402,  401,  400,  397,  323,  323,  323,
      323,  323,  323,  500,  396,  500,  393,  500,  500,  501,
      390,  501,  501,  501,  501,  502,  388,  387,  502,  502,
      502,  503,  503,  504,  386,  504,  504,  504,  504,  505,
      385,  505,  505,  505,  505,  506,  384,  506,  506,  506,
      506,  507,  383,  507,  507,  507,  507,  509,  509,  509,
      509,  509,  509,  510,  510,  510,  510,  510,  510,  511,

      511,  511,  511,  511,  511,  512,  512,  512,  512,  512,
      512,  381,  380,  379,  378,  376,  374,  371,  370,  369,
      368,  365,  364,  361,  358,  357,  356,  354,  353,  352,
      351,  350,  349,  347,  346,  345,  344,  343,  341,  340,
      339,  338,  337,  334,  333,  332,  331,  329,  328,  327,
      326,  314,  313,  312,  310,  309,  308,  307,  306,  305,
      303,  302,  301,  300,  299,  297,  296,  295,  294,  293,
      290,  289,  288,  287,  285,  284,  283,  282,  269,  268,
      267,  266,  265,  264,  262,  261,  259,  258,  257,  254,
      252,  251,  250,  249,  245,  244,  243,  242,  241,  238,

      236,  235,  234,  232,  227,  216,  210,  208,  202,  193,
      192,  191,  190,  189,  188,  186,  185,  183,  182,  181,
      178,  176,  175,  174,  173,  169,  168,  167,  166,  165,
      162,  160,  159,  158,  156,  151,  140,  134,  133,  132,
      127,  126,  121,  119,  116,  115,  112,  111,  110,  108,
      105,  103,   99,   95,   93,   91,   87,   72,   71,   68,
       60,   58,   55,   54,   51,   50,   49,   47,   44,   42,
       38,   34,   32,   30,   26,   11,   10,    7,    3,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,

      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499,  499,  499,  499,  499,  499,  499,  499,  499,
      499,  499
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[107] =
    {   0,
1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#line 3 "scan.l"
#include <stdlib.h>
#include <stdio.h>
#include "parser.tab.h" // Get tokens from bison
#include <string.h>



int nesting = 0 ; 

unsigned int level = 0 ;
int level_start[100];
int linee =1;
unsigned int first = 1 ;
unsigned int flag = 0;
unsigned int line =0;
void process_indent(char* line) ;
void unputt(int leng);
#line 872 "lex.yy.c"
#line 873 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 52 "scan.l"



#line 1097 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 500 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 880 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 55 "scan.l"
{/* Ignore blank lines. */ linee++ ;} 			
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 56 "scan.l"
{/* Ignore blank lines. */ ;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 57 "scan.l"
{process_indent(yytext); unputt(yyleng);/*Reads every line*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 58 "scan.l"
{ /*Ignore comments*/}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "scan.l"
{level++ ; flag = 1;  return IF;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "scan.l"
{level++ ; flag = 1;  return FOR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "scan.l"
{level++ ; flag = 1;  return DEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "scan.l"
{level++ ; flag = 1;  return CLASS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "scan.l"
{level++ ; flag = 1;  return ELIF;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "scan.l"
{level++ ; flag = 1;  return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "scan.l"
{return SETDEFAULT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "scan.l"
{return FALSE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "scan.l"
{return NONE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "scan.l"
{return TRUE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "scan.l"
{return AND;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "scan.l"
{return AS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "scan.l"
{return ASSERT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "scan.l"
{return BREAK;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "scan.l"
{return CONTINUE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "scan.l"
{return DEL;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "scan.l"
{return EXCEPT;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "scan.l"
{return FINALLY; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "scan.l"
{return FROM; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "scan.l"
{return GLOBAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "scan.l"
{return IMPORT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "scan.l"
{return IN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "scan.l"
{return IS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "scan.l"
{return LAMBDA;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 85 "scan.l"
{return NOT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "scan.l"
{return OR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "scan.l"
{return PASS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 88 "scan.l"
{return RAISE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 89 "scan.l"
{return RETURN;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 90 "scan.l"
{return TRY;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 91 "scan.l"
{return WHILE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 92 "scan.l"
{return WITH;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "scan.l"
{return YIELD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "scan.l"
{return RANGE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "scan.l"
{return PRINT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "scan.l"
{return EXEC;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 "scan.l"
{return ITEMS;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "scan.l"
{return 'L';}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "scan.l"
{return 'l';}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 101 "scan.l"
{return INC;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 102 "scan.l"
{return DEC;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 103 "scan.l"
{return APOSTROPHE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 104 "scan.l"
{return QUOTATION;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 105 "scan.l"
{return ELLIPSIS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "scan.l"
{return RIGHT_ASSIGN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 107 "scan.l"
{return LEFT_ASSIGN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 108 "scan.l"
{return ADD_ASSIGN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 109 "scan.l"
{return SUB_ASSIGN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 110 "scan.l"
{return MUL_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "scan.l"
{return POW_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 "scan.l"
{return DIV_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "scan.l"
{return MOD_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "scan.l"
{return AND_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 115 "scan.l"
{return XOR_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 116 "scan.l"
{return OR_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 117 "scan.l"
{return RIGHT_OP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 118 "scan.l"
{return LEFT_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 119 "scan.l"
{return LE_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 120 "scan.l"
{return GE_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 121 "scan.l"
{return EQ_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 122 "scan.l"
{return NE_OP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 123 "scan.l"
{return LR_OP;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 124 "scan.l"
{return EXA;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 125 "scan.l"
{return COL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 126 "scan.l"
{return '_';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 127 "scan.l"
{return COMMA;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 128 "scan.l"
{return COLON;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 129 "scan.l"
{return EQUAL;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 130 "scan.l"
{nesting++; return LPAR;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 131 "scan.l"
{nesting--; return RPAR;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 132 "scan.l"
{return '[';}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 133 "scan.l"
{return ']';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 134 "scan.l"
{return LBRA;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 135 "scan.l"
{return RBRA;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 136 "scan.l"
{return DOT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 137 "scan.l"
{return AND_EXP;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 138 "scan.l"
{return PAPAKI;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 139 "scan.l"
{return '~';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 140 "scan.l"
{return MINUS;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 141 "scan.l"
{return PLUS;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 142 "scan.l"
{return PERCENT;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 143 "scan.l"
{return LESS_THAN_OP;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 144 "scan.l"
{return GREATER_THAN_OP;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 145 "scan.l"
{return XOR;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 146 "scan.l"
{return OR_SIGN;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 147 "scan.l"
{return '`'; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 148 "scan.l"
{return STAR;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 149 "scan.l"
{return DOUBLESTAR;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 150 "scan.l"
{return SLASH;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 151 "scan.l"
{return DOUBLESLASH;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 153 "scan.l"
{	
				strcpy(yylval.nval.name, yytext);
				yylval.nval.type = IDENT;
				yylval.nval.data_type = LITERAL;
				return IDENTIFIER;
			}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 160 "scan.l"
{	
				yylval.nval.ival = atoi(yytext);
				yylval.nval.type = INTEGER;
				yylval.nval.data_type = LITERAL;
				return DECINTEGER;
			}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 167 "scan.l"
{	
				yylval.nval.ival = atoi(yytext);
				yylval.nval.type = INTEGER;
				yylval.nval.data_type = LITERAL;
				return OCTINTEGER;
			}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 174 "scan.l"
{	
				yylval.nval.ival = atoi(yytext);
				yylval.nval.type = INTEGER;
				yylval.nval.data_type = LITERAL;
				return HEXINTEGER;
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 181 "scan.l"
{	yylval.nval.fval = atof(yytext);
				yylval.nval.type = FLOAT;
				yylval.nval.data_type = LITERAL;
				
				return POINTFLOAT;
			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 188 "scan.l"
{	yylval.nval.fval = atof(yytext);
				yylval.nval.type = FLOAT;
				yylval.nval.data_type = LITERAL;
				
				return EXPONENTFLOAT;
			}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 195 "scan.l"
{	
				
				return IMAGNUMBER;
			}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 201 "scan.l"
{strcpy(yylval.nval.string, yytext);
				yylval.nval.type = STRING;
				yylval.nval.data_type = LITERAL;
				
				return SHORTSTRING;
			}
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 208 "scan.l"
{	
				
				strcpy(yylval.nval.string, yytext);
				yylval.nval.type = STRING;
				yylval.nval.data_type = LITERAL	;
				
				return LONGSTRING;
			}
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 219 "scan.l"
{
				linee++;
				//return NEWLINE;	
			}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 225 "scan.l"
{/* Do nothing */}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 228 "scan.l"
{ return 0 ; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 230 "scan.l"
ECHO;
	YY_BREAK
#line 1751 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 500 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 500 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 499);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 230 "scan.l"

//Python Indentation 
void unputt(int leng){
	int last = leng - 1;
	
        while ((last >= 0)) {
                unput(yytext[last]);
                last--;}

}

unsigned int white_count(char* line) {
  unsigned int count = 0 ;

  while (*line == ' ' || *line == '\t'){
	if(*line == ' ')
		count++;
	else
		count = count + 8;
	
	line++;   
	     
 }
   
   return count;
}

void process_indent(char* line) {

 
  if (nesting)
    /* Ignore indents while nested. */
    return ;

  unsigned int indent = white_count(line) ;
 

  if ((indent ==level_start[level] && !flag) ||(flag && indent >level_start[level-1])) {
    
    level_start[level] = indent;
    flag=0;
    return ;
  }
  else if(flag){
	printf("Line:%d --> Indentation error\n",linee);
	return;}	

   if (indent > level_start[level] && !flag) {
	
    printf("Line:%d --> Indentation error\n",linee);
    return ;
  }
   
  int temp = level;
  while(indent != level_start[temp] && level >=0) {
    flag=0;
    temp--;
    
  }

  if(temp>=0)
	level = temp ;
  else
	printf("Line:%d --> Indentation error\n",linee);
return;



  
}

