
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 104
#define YY_END_OF_BUFFER 105
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[476] =
    {   0,
        0,    0,  105,  104,  102,  103,   65,   45,    4,   83,
       78,   44,   71,   72,   89,   82,   68,   81,   77,   91,
       94,   94,   69,   66,   84,   70,   85,   79,   93,   93,
       40,   93,   93,   93,   93,   73,   74,   86,   67,   88,
       93,   93,   93,   93,   93,   93,   93,   93,   41,   93,
       93,   93,   93,   93,   93,   93,   93,   75,   87,   76,
       80,    3,    3,    1,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,   63,    0,  100,  100,    0,    4,   54,   55,    0,
      100,  100,    0,   90,   51,   42,   49,   43,   50,    0,
       97,   92,   53,   97,   95,    0,    0,   99,    0,   94,
       59,   60,   64,   62,   61,   58,   93,   93,   93,    0,
        0,   93,   93,   56,   93,   15,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,    5,   93,   25,   26,
       93,   93,   29,   93,   93,   93,   93,   93,   93,   93,
       93,   57,    3,    3,    2,    1,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,  100,    0,
        0,   52,   46,   97,    0,   98,   96,   48,   47,   93,
       93,    0,   93,   14,   93,   93,   93,   93,    7,   19,
       93,   93,   93,   93,   93,    6,   93,   93,   93,   93,

       28,   93,   93,   93,   93,   93,   33,   93,   93,   93,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    0,    0,    0,    0,    0,    0,   93,   12,
       13,   93,   93,   93,   93,    9,   10,   93,   39,   93,
       22,   93,   93,   93,   30,   93,   93,   93,   93,   93,
       35,   93,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    0,    0,   11,   93,   17,    8,   93,   93,
       93,   93,   93,   93,   38,   31,   37,   93,   34,   36,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,  101,  101,
       16,   93,   20,   93,   23,   24,   27,   32,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   93,   21,
        3,    3,   18,    3,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    1,   28,   29,   29,   29,   29,   30,   31,
       32,   32,   32,   33,   32,   34,   32,   35,   32,   32,
       32,   36,   32,   37,   38,   32,   32,   39,   32,   32,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   32,   62,   63,   64,   65,   32,   66,   67,
       68,   32,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        4,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1,    1,    6,    1,    5,    5,    5,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[489] =
    {   0,
        0,   72,  897,  898,  898,  898,  870,  140,    0,  869,
      868,  141,  898,  898,  134,  135,  898,  132,  133,  137,
      144,  158,  898,  898,  142,  867,  144,  898,    0,  846,
        0,  831,  178,  828,  179,  898,  898,  863,    0,  898,
      133,  826,  115,  837,  130,  141,  829,  147,  839,  824,
      821,  111,  193,  820,  209,  164,  827,  898,  854,  898,
      898,    0,  219,  898,    0,  204,  853,  218,    0,  852,
      851,  219,    0,    0,  188,  212,    0,  167,  213,  193,
      228,  235,    0,    0,  237,  850,  210,    0,  295,  829,
        0,  814,  221,  811,  361,    0,    0,  846,    0,    0,

      181,  809,  194,  820,  185,  212,  812,  218,  822,  807,
      804,  224,  362,  803,  363,  226,  810,    0,  837,    0,
        0,  898,  370,  373,  855,  850,    0,  898,  898,  374,
      376,  849,  852,  832,  898,  898,  898,  898,  898,  839,
      371,  898,  898,  398,  412,  419,  267,  898,    0,  438,
      830,  898,  898,  898,  898,  829,    0,  797,  794,  845,
      383,  786,  287,  898,  801,  786,  798,  801,  787,  325,
      332,  225,  786,  782,  783,  782,    0,  780,    0,    0,
      782,  775,    0,  775,  783,  330,  772,  767,  780,  769,
      782,  898,    0,  289,  898,  898,  393,    0,  395,  402,

      824,    0,    0,    0,    0,  439,  450,  819,    0,  803,
        0,    0,    0,    0,    0,  810,  456,    0,    0,  462,
      480,  498,  512,    0,  534,  519,  801,    0,    0,    0,
        0,  800,    0,  768,  765,  816,  468,  757,  440,    0,
      772,  757,  769,  772,  758,  359,  375,  355,  757,  753,
      754,  753,    0,  751,    0,    0,  753,  746,    0,  746,
      754,  368,  743,  738,  751,  740,  753,    0,  898,  458,
      485,  898,  898,  537,  483,  540,    0,  898,  898,  739,
      751,  793,  749,    0,  748,  751,  733,  731,    0,    0,
      743,  743,  742,  743,  744,    0,  731,  741,  727,  739,

        0,  722,  725,  720,  730,  716,    0,  723,  726,  721,
        0,  572,  583,    0,    0,  576,  501,  579,  615,    0,
        0,  686,  693,  730,  681,    0,  674,  677,  654,  649,
        0,    0,  660,  658,  657,  657,  658,    0,  645,  655,
      641,  653,    0,  636,  639,  634,  644,  630,    0,  637,
      639,  634,  531,  537,  687,  597,  599,  686,  638,    0,
        0,  625,  628,  620,  628,    0,    0,  620,    0,  623,
        0,  632,  615,  627,    0,  611,  624,  617,  598,  608,
        0,  594,  586,  600,  639,  611,  612,  629,  580,    0,
        0,  567,  572,  558,  557,    0,    0,  529,    0,  519,

        0,  525,  506,  517,    0,  487,  500,  497,  484,  495,
        0,  494,  613,  614,    0,  461,    0,    0,  465,  451,
      457,  451,  443,  451,    0,    0,    0,  435,    0,    0,
      644,  645,    0,  423,    0,    0,  426,  417,  415,  413,
      402,  418,    0,    0,    0,  395,    0,    0,  652,  628,
        0,  370,    0,  322,    0,    0,    0,    0,  665,  668,
        0,  318,    0,  303,    0,    0,    0,    0,  243,    0,
      197,    0,    0,    0,  898,  709,  715,  721,  723,  729,
      735,  741,  747,  154,  753,  759,  765,  771
    } ;

static const flex_int16_t yy_def[489] =
    {   0,
      475,  475,  475,  475,  475,  475,  475,  476,  477,  475,
      475,  478,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  479,  479,
      479,  479,  479,  479,  479,  475,  475,  475,  479,  475,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  475,  475,  475,
      475,  480,  480,  475,  480,  480,  480,  481,  482,  480,
      480,  483,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  475,   89,
       89,   89,   89,   89,   89,  480,  480,  480,   89,  480,

       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,  480,  480,  480,
      480,  475,  476,  476,  475,  476,  477,  475,  475,  478,
      478,  475,  478,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  484,  475,
      475,  475,  475,  475,  475,  475,  479,  479,  479,  475,
      478,  479,  479,  475,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  475,  480,  480,  475,  475,  480,  480,  481,  481,

      480,  481,  482,  480,  480,  483,  483,  480,  483,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  480,  480,  480,  480,  480,  480,
      480,  480,   89,   89,   89,  480,  483,   89,   89,  480,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,  480,  475,  485,
      486,  475,  475,  475,  475,  475,  484,  475,  475,  479,
      479,  475,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      480,  487,  488,  480,  480,  480,  480,  480,  480,  480,
      480,   89,   89,  480,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,  485,  485,  485,  486,  486,  486,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  487,  487,  487,  488,  488,  488,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,

       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,  485,  486,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      487,  488,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,  485,  486,
      479,  479,  479,  479,  479,  479,  479,  479,  487,  488,
       89,   89,   89,   89,   89,   89,   89,   89,  479,  479,
       89,   89,  479,   89,    0,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475
    } ;

static const flex_int16_t yy_nxt[971] =
    {   0,
        4,    4,    5,    6,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   23,   24,   25,   26,   27,   28,   29,   29,
       30,   29,   29,   31,   32,   33,   34,   35,   29,   36,
        4,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   29,   48,   29,   29,   49,   29,   50,   51,
       52,   53,   29,   54,   55,   56,   29,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   82,   83,   84,   85,   86,   87,   88,

       89,   89,   90,   89,   89,   91,   92,   93,   94,   95,
       89,   96,   62,   97,   98,   99,  100,  101,  102,  103,
      104,  105,  106,  107,   89,  108,   89,   89,  109,   89,
      110,  111,  112,  113,   89,  114,  115,  116,   89,  117,
      118,  119,  120,  121,  124,  131,  125,  134,  138,  136,
      140,  132,  141,  141,  141,  142,  184,  139,  277,  135,
      137,  144,  143,  145,  145,  146,  151,  152,  153,  155,
      156,  168,  185,  147,  169,  144,  148,  150,  150,  150,
      126,  133,  149,  214,  160,  160,  171,  147,  161,  161,
      148,  165,  215,  147,  173,  166,  172,  177,  148,  160,

      174,  210,  175,  161,  178,  179,  196,  147,  197,  180,
      149,  218,  148,  211,  163,  160,  189,  190,  219,  161,
      194,  195,  200,  207,  201,  193,  212,  236,  193,  208,
      216,  237,  217,  217,  217,  231,  232,  213,  186,  241,
      163,  247,  187,  242,  163,  220,  474,  221,  221,  222,
      244,  248,  220,  245,  226,  226,  226,  223,  202,  209,
      224,  227,  228,  229,  223,  249,  225,  224,  253,  260,
      163,  250,  293,  251,  294,  254,  255,  223,  265,  266,
      256,  275,  224,  275,  223,  261,  276,  276,  276,  224,
      194,  195,  473,  160,  225,  193,  193,  161,  193,  193,

      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  233,  233,  233,  193,  193,  193,
      193,  193,  193,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  193,  193,  193,  193,  233,  193,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  193,  193,  193,  193,  236,  236,  236,
      472,  237,  237,  237,  124,  289,  269,  124,  131,  269,
      131,  290,  471,  304,  269,  291,  269,  131,  305,  470,
      141,  141,  141,  132,  292,  196,  239,  197,  239,  200,

      147,  311,  335,  148,  336,  193,  200,  262,  311,  331,
      126,  263,  193,  126,  133,  332,  133,  274,  274,  274,
      147,  346,  239,  133,  239,  148,  347,  147,  333,  144,
      148,  145,  145,  146,  469,  202,  144,  334,  146,  146,
      146,  147,  202,  207,  148,  193,  236,  147,  147,  311,
      237,  148,  148,  468,  207,  144,  193,  150,  150,  150,
      311,  147,  354,  467,  354,  466,  148,  147,  147,  465,
      148,  464,  207,  148,  193,  217,  217,  217,  208,  209,
      463,  316,  316,  316,  462,  223,  461,  147,  224,  357,
      209,  223,  148,  458,  224,  357,  457,  220,  355,  221,

      221,  222,  276,  276,  276,  223,  456,  455,  209,  223,
      224,  223,  224,  454,  453,  220,  224,  222,  222,  222,
      318,  318,  318,  452,  451,  358,  317,  223,  317,  223,
      224,  318,  318,  318,  224,  354,  220,  354,  226,  226,
      226,  413,  448,  413,  447,  446,  445,  223,  223,  444,
      443,  224,  224,  319,  319,  319,  274,  274,  274,  276,
      276,  276,  319,  319,  319,  442,  147,  441,  223,  148,
      440,  355,  148,  224,  353,  439,  384,  355,  384,  319,
      319,  319,  319,  319,  319,  356,  147,  387,  353,  438,
      384,  148,  384,  387,  148,  316,  316,  316,  318,  318,

      318,  357,  353,  414,  431,  223,  431,  357,  224,  414,
      437,  224,  385,  356,  356,  387,  432,  449,  450,  449,
      436,  387,  432,  388,  450,  223,  385,  435,  434,  433,
      224,  475,  450,  224,  319,  319,  319,  358,  450,  358,
      385,  475,  430,  319,  319,  319,  353,  356,  459,  460,
      459,  388,  388,  355,  358,  460,  449,  429,  449,  428,
      319,  319,  319,  319,  319,  319,  427,  353,  358,  459,
      356,  459,  460,  426,  425,  424,  423,  422,  460,  421,
      420,  419,  418,  417,  385,  388,  416,  415,  475,  475,
      412,  411,  355,  410,  409,  408,  407,  406,  405,  404,

      403,  402,  401,  400,  399,  385,  398,  397,  388,  123,
      396,  123,  395,  123,  123,  127,  394,  127,  127,  127,
      127,  130,  393,  392,  130,  130,  130,  157,  157,  193,
      391,  193,  193,  193,  193,  199,  312,  199,  199,  199,
      199,  203,  390,  203,  203,  203,  203,  206,  389,  206,
      206,  206,  206,  353,  353,  353,  353,  353,  353,  356,
      356,  356,  356,  356,  356,  383,  383,  383,  383,  383,
      383,  386,  386,  386,  386,  386,  386,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  270,

      360,  359,  352,  351,  350,  349,  348,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  315,  314,  313,
      312,  310,  309,  308,  307,  306,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  273,  272,  130,  271,
      123,  270,  268,  267,  264,  259,  258,  257,  252,  246,
      243,  240,  238,  235,  234,  230,  205,  204,  198,  192,
      191,  188,  183,  182,  181,  176,  170,  167,  164,  162,
      159,  158,  154,  129,  128,  122,  475,    3,  475,  475,

      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475
    } ;

static const flex_int16_t yy_chk[971] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    8,   12,    8,   15,   18,   16,
       19,   12,   19,   19,   19,   20,   52,   18,  484,   15,
       16,   21,   20,   21,   21,   21,   25,   25,   25,   27,
       27,   43,   52,   21,   43,   22,   21,   22,   22,   22,
        8,   12,   21,   78,   33,   35,   45,   22,   33,   35,
       22,   41,   78,   21,   46,   41,   45,   48,   21,   53,

       46,   75,   46,   53,   48,   48,   66,   22,   66,   48,
       21,   80,   22,   75,   35,   55,   56,   56,   80,   55,
       63,   63,   68,   72,   68,   72,   76,   93,   68,   72,
       79,   93,   79,   79,   79,   87,   87,   76,   53,  101,
       35,  105,   53,  101,   55,   81,  471,   81,   81,   81,
      103,  105,   82,  103,   82,   82,   82,   81,   68,   72,
       81,   85,   85,   85,   82,  106,   81,   82,  108,  112,
       55,  106,  172,  106,  172,  108,  108,   81,  116,  116,
      108,  147,   81,  147,   82,  112,  147,  147,  147,   82,
      194,  194,  469,  163,   81,   89,   89,  163,   89,   89,

       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   95,  113,  115,
      464,   95,  113,  115,  123,  170,  123,  124,  130,  124,
      131,  170,  462,  186,  130,  171,  131,  161,  186,  454,
      141,  141,  141,  161,  171,  197,   95,  197,  115,  199,

      141,  199,  248,  141,  248,  199,  200,  113,  200,  246,
      123,  113,  200,  124,  130,  246,  131,  144,  144,  144,
      141,  262,   95,  161,  115,  141,  262,  144,  247,  145,
      144,  145,  145,  145,  452,  199,  146,  247,  146,  146,
      146,  145,  200,  206,  145,  206,  239,  144,  146,  206,
      239,  146,  144,  446,  207,  150,  207,  150,  150,  150,
      207,  145,  270,  442,  270,  441,  145,  150,  146,  440,
      150,  439,  237,  146,  237,  217,  217,  217,  237,  206,
      438,  220,  220,  220,  437,  217,  434,  150,  217,  271,
      207,  220,  150,  428,  220,  271,  424,  221,  270,  221,

      221,  221,  275,  275,  275,  217,  423,  422,  237,  221,
      217,  220,  221,  421,  420,  222,  220,  222,  222,  222,
      317,  317,  317,  419,  416,  271,  223,  222,  223,  221,
      222,  223,  223,  223,  221,  353,  226,  353,  226,  226,
      226,  354,  412,  354,  410,  409,  408,  222,  226,  407,
      406,  226,  222,  225,  225,  225,  274,  274,  274,  276,
      276,  276,  225,  225,  225,  404,  274,  403,  226,  274,
      402,  353,  276,  226,  312,  400,  312,  354,  312,  225,
      225,  225,  225,  225,  225,  313,  274,  313,  383,  398,
      383,  274,  383,  313,  276,  316,  316,  316,  318,  318,

      318,  356,  384,  357,  384,  316,  384,  356,  316,  357,
      395,  318,  312,  386,  387,  386,  387,  413,  414,  413,
      394,  386,  387,  313,  414,  316,  383,  393,  392,  389,
      316,  388,  450,  318,  319,  319,  319,  356,  450,  357,
      384,  385,  382,  319,  319,  319,  431,  432,  431,  432,
      431,  386,  387,  413,  414,  432,  449,  380,  449,  379,
      319,  319,  319,  319,  319,  319,  378,  459,  450,  459,
      460,  459,  460,  377,  376,  374,  373,  372,  460,  370,
      368,  365,  364,  363,  431,  432,  362,  359,  358,  355,
      352,  351,  449,  350,  348,  347,  346,  345,  344,  342,

      341,  340,  339,  337,  336,  459,  335,  334,  460,  476,
      333,  476,  330,  476,  476,  477,  329,  477,  477,  477,
      477,  478,  328,  327,  478,  478,  478,  479,  479,  480,
      325,  480,  480,  480,  480,  481,  324,  481,  481,  481,
      481,  482,  323,  482,  482,  482,  482,  483,  322,  483,
      483,  483,  483,  485,  485,  485,  485,  485,  485,  486,
      486,  486,  486,  486,  486,  487,  487,  487,  487,  487,
      487,  488,  488,  488,  488,  488,  488,  310,  309,  308,
      306,  305,  304,  303,  302,  300,  299,  298,  297,  295,
      294,  293,  292,  291,  288,  287,  286,  285,  283,  282,

      281,  280,  267,  266,  265,  264,  263,  261,  260,  258,
      257,  254,  252,  251,  250,  249,  245,  244,  243,  242,
      241,  238,  236,  235,  234,  232,  227,  216,  210,  208,
      201,  191,  190,  189,  188,  187,  185,  184,  182,  181,
      178,  176,  175,  174,  173,  169,  168,  167,  166,  165,
      162,  160,  159,  158,  156,  151,  140,  134,  133,  132,
      126,  125,  119,  117,  114,  111,  110,  109,  107,  104,
      102,   98,   94,   92,   90,   86,   71,   70,   67,   59,
       57,   54,   51,   50,   49,   47,   44,   42,   38,   34,
       32,   30,   26,   11,   10,    7,    3,  475,  475,  475,

      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scan.l"
#line 2 "scan.l"
#include <stdlib.h>
#include <stdio.h>
#include "parser.tab.h" // Get tokens from bison
#include <string.h>



int nesting = 0 ; 

unsigned int level = 0 ;
int level_start[100];
int linee =1;
unsigned int first = 1 ;
unsigned int flag = 0;
unsigned int line =0;
void process_indent(char* line) ;
void unputt(int leng);
#line 834 "lex.yy.c"
#line 835 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 51 "scan.l"



#line 1059 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 476 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 898 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 54 "scan.l"
{/* Ignore blank lines. */ linee++ ;} 			
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 55 "scan.l"
{/* Ignore blank lines. */ ;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 56 "scan.l"
{process_indent(yytext); unputt(yyleng);/*Reads every line*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "scan.l"
{ /*Ignore comments*/}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 60 "scan.l"
{level++ ; flag = 1;  return IF;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "scan.l"
{level++ ; flag = 1;  return FOR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 62 "scan.l"
{level++ ; flag = 1;  return DEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "scan.l"
{level++ ; flag = 1;  return CLASS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 64 "scan.l"
{level++ ; flag = 1;  return ELIF;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 65 "scan.l"
{level++ ; flag = 1;  return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "scan.l"
{return FALSE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "scan.l"
{return NONE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "scan.l"
{return TRUE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "scan.l"
{return AND;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "scan.l"
{return AS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "scan.l"
{return ASSERT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "scan.l"
{return BREAK;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "scan.l"
{return CONTINUE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "scan.l"
{return DEL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "scan.l"
{return EXCEPT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "scan.l"
{return FINALLY; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "scan.l"
{return FROM; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "scan.l"
{return GLOBAL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "scan.l"
{return IMPORT;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "scan.l"
{return IN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "scan.l"
{return IS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "scan.l"
{return LAMBDA;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "scan.l"
{return NOT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 85 "scan.l"
{return OR;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "scan.l"
{return PASS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "scan.l"
{return RAISE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 88 "scan.l"
{return RETURN;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 89 "scan.l"
{return TRY;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 90 "scan.l"
{return WHILE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 91 "scan.l"
{return WITH;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 92 "scan.l"
{return YIELD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "scan.l"
{return RANGE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "scan.l"
{return PRINT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "scan.l"
{return EXEC;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 97 "scan.l"
{return 'L';}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "scan.l"
{return 'l';}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 100 "scan.l"
{return INC;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "scan.l"
{return DEC;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 102 "scan.l"
{return APOSTROPHE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 103 "scan.l"
{return QUOTATION;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 104 "scan.l"
{return ELLIPSIS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 105 "scan.l"
{return RIGHT_ASSIGN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 106 "scan.l"
{return LEFT_ASSIGN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 107 "scan.l"
{return ADD_ASSIGN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 108 "scan.l"
{return SUB_ASSIGN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 109 "scan.l"
{return MUL_ASSIGN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 110 "scan.l"
{return POW_ASSIGN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 111 "scan.l"
{return DIV_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 112 "scan.l"
{return MOD_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 113 "scan.l"
{return AND_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 114 "scan.l"
{return XOR_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 115 "scan.l"
{return OR_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "scan.l"
{return RIGHT_OP; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 117 "scan.l"
{return LEFT_OP; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "scan.l"
{return LE_OP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "scan.l"
{return GE_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 120 "scan.l"
{return EQ_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 121 "scan.l"
{return NE_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 122 "scan.l"
{return LR_OP;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 123 "scan.l"
{return EXA;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 124 "scan.l"
{return COL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 125 "scan.l"
{return '_';}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 126 "scan.l"
{return COMMA;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 127 "scan.l"
{return COLON;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 128 "scan.l"
{return EQUAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 129 "scan.l"
{nesting++; return LPAR;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 130 "scan.l"
{nesting--; return RPAR;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 131 "scan.l"
{return '[';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 132 "scan.l"
{return ']';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 133 "scan.l"
{return LBRA;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 134 "scan.l"
{return RBRA;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 135 "scan.l"
{return DOT;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 136 "scan.l"
{return AND_EXP;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 137 "scan.l"
{return PAPAKI;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 138 "scan.l"
{return '~';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 139 "scan.l"
{return MINUS;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 140 "scan.l"
{return PLUS;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 141 "scan.l"
{return PERCENT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 142 "scan.l"
{return LESS_THAN_OP;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 143 "scan.l"
{return GREATER_THAN_OP;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 144 "scan.l"
{return XOR;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 145 "scan.l"
{return OR_SIGN;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 146 "scan.l"
{return '`'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 147 "scan.l"
{return STAR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 148 "scan.l"
{return DOUBLESTAR;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 149 "scan.l"
{return SLASH;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 150 "scan.l"
{return DOUBLESLASH;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 152 "scan.l"
{	
				strcpy(yylval.nval.name, yytext);
				yylval.nval.type = IDENT;
				yylval.nval.data_type = LITERAL;
				printf("IDENTIFIER: %s\n", yytext);
				return IDENTIFIER;
			}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 160 "scan.l"
{	
				yylval.nval.ival = atoi(yytext);
				yylval.nval.type = INTEGER;
				yylval.nval.data_type = LITERAL;
				printf("DECINTEGER: %s\n", yytext);
				return DECINTEGER;
			}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 168 "scan.l"
{	
				yylval.nval.ival = atoi(yytext);
				yylval.nval.type = INTEGER;
				yylval.nval.data_type = LITERAL;
				printf("OCTINTEGER: %s\n", yytext);
				return OCTINTEGER;
			}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 176 "scan.l"
{	
				yylval.nval.ival = atoi(yytext);
				yylval.nval.type = INTEGER;
				yylval.nval.data_type = LITERAL;
				printf("HEXINTEGER: %s\n", yytext);
				return HEXINTEGER;
			}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 184 "scan.l"
{	yylval.nval.fval = atof(yytext);
				yylval.nval.type = FLOAT;
				yylval.nval.data_type = LITERAL;
				printf("POINTFLOAT: %s\n", yytext);
				return POINTFLOAT;
			}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 191 "scan.l"
{	yylval.nval.fval = atof(yytext);
				yylval.nval.type = FLOAT;
				yylval.nval.data_type = LITERAL;
				printf("EXPONENTFLOAT: %s\n", yytext);
				return EXPONENTFLOAT;
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 198 "scan.l"
{	
				printf("IMAGNUMBER: %s\n", yytext);
				return IMAGNUMBER;
			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 204 "scan.l"
{	strcpy(yylval.nval.string, yytext);
				yylval.nval.type = STRING;
				yylval.nval.data_type = LITERAL;
				printf("SHORTSTRING: %s\n", yytext);
				return SHORTSTRING;
			}
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 211 "scan.l"
{	
				
				strcpy(yylval.nval.string, yytext);
				yylval.nval.type = STRING;
				yylval.nval.data_type = LITERAL	;
				printf("LONGSTRING: %s\n", yytext);
				return LONGSTRING;
			}
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 222 "scan.l"
{
				linee++;
						
			}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 228 "scan.l"
{/* Do nothing */}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 231 "scan.l"
{ return 0 ; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 233 "scan.l"
ECHO;
	YY_BREAK
#line 1697 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 476 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 476 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 475);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 233 "scan.l"

//Python Indentation 
void unputt(int leng){
	int last = leng - 1;
	
        while ((last >= 0)) {
                unput(yytext[last]);
                last--;}

}

unsigned int white_count(char* line) {
  unsigned int count = 0 ;

  while (*line == ' ' || *line == '\t'){
	if(*line == ' ')
		count++;
	else
		count = count + 8;
	
	line++;   
	     
 }
   
   return count;
}

void process_indent(char* line) {

 
  if (nesting)
    /* Ignore indents while nested. */
    return ;

  unsigned int indent = white_count(line) ;
 

  if ((indent ==level_start[level] && !flag) ||(flag && indent >level_start[level-1])) {
    
    level_start[level] = indent;
    flag=0;
    return ;
  }
  else if(flag){
	printf("Line:%d --> Indentation error\n",linee);
	return;}	

   if (indent > level_start[level] && !flag) {
	
    printf("Line:%d --> Indentation error\n",linee);
    return ;
  }
   
  int temp = level;
  while(indent != level_start[temp] && level >=0) {
    flag=0;
    temp--;
    
  }

  if(temp>=0)
	level = temp ;
  else
	printf("Line:%d --> Indentation error\n",linee);
return;



  
}

